version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          name: Android build
          command: ./gradlew build
  lint:
    executor: android/android
    steps:
      - run:
          name: Android Lint
          command: ./gradlew lint
  test:
    executor: android/android
      steps:
          - run:
            name: Android Test
            command: ./gradlew jacocoTestReport